#
# Copyright (c) 2021 Nordic Semiconductor ASA
# Copyright (c) 2025 HU Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
manifest:
  defaults:
    remote: upstream
  self:
    path: sdk
    west-commands: scripts/west-commands.yml
    import: submanifests

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: babblesim
      url-base: https://github.com/BabbleSim
    # https://github.com/bjarki-andreasen/zephyr-micropython/
    - name: bjarki-andreasen
      url-base: https://github.com/bjarki-andreasen

  group-filter: [-babblesim, -optional]

  projects:
    - name: zephyr
      remote: upstream
      revision: main
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis
          - cmsis-dsp
          - cmsis-nn
          - cmsis_6
          - hal_nxp
          - hal_st
          - hal_stm32
          - littlefs
          - lvgl
          - mbedtls
          - mcuboot
          - percepio
          - picolibc
          - segger
          - tf-psa-crypto
          - tinycrypt
          - zcbor

    - name: etc-data
      url: http://github.com/doyoonk/etcz.git
      revision: main
      path: etc

    - name: s2opc
      groups:
        - s2opc
      path: modules/lib/s2opc
      revision: master
      url: https://gitlab.com/systerel/S2OPC.git

    - name: micropython
      path: modules/lib/micropython
      revision: master
      url: https://github.com/micropython/micropython.git
      submodules: #true  # Automatically updates all submodules in this repo
        - path: lib/micropython-lib
    # https://github.com/bjarki-andreasen/zephyr-micropython/
    #- name: micropython
    #  remote: bjarki-andreasen
    #  revision: aceafd9e98151dd6f32ff142055947f0f32beeda
    #  path: modules/lib/micropython
    #  submodules:
    #    - path: lib/micropython-lib
